### ISSUE TITLE
Panel Is Opaque Even With No Window Touching It

### ISSUE THREAD

**Issue by weltenweber** [jderose9/dash-to-panel#276]
On Ubuntu 17.10 with `gnome-session` installed and active, the panel turns completely opaque whenever a window is open, regardless of whether it’s actually touching the panel or is maximised.

As far as I know the default behaviour in GNOME 3.26.1 is that the panel only turns opaque if a window is touching it.

*Edit:* It seems to only occur if the panel is set to display on the bottom of the screen.

**Comment by jderose9** [comment]
Hi. This was fixed in v10. Do you have that version or later installed?

**Comment by weltenweber** [comment]
I had just updated to v11, however, I was still seeing the issue. After rebooting it seems to be fixed, though. Sorry for the inconvenience and thanks for the quick reply!
