### ISSUE TITLE
Appearance -> "Tray Font Size" is not applied to the input language indicator on load

### ISSUE THREAD

**Issue by RomanShumikhin** [jderose9/dash-to-panel#34]
I am running Antergos Linux (64-bit) with Gnome version 3.22.2 at 4K resolution with Tweaks -> Fonts -> Scaling Factor set to 1.50 and Tweaks -> Windows -> HiDPI -> Window Scaling set to 2.
I have 3 input sources set: English (US), Russian and Japanese (Anthy). I adjusted the tray font size and set it to 16px because the original size was too small in 4K. Everything works fine when you change the value, but after restarting Gnome the styles are not applied to the language indicator.

I can always reproduce this issue just by restarting gnome-shell (by typing 'r' in the "Enter a Command" dialog).

Please check the screenshot. I have some experience with gjs and can test any workarounds for that if needed.

Right now I have open Dash-To-Panel settings every time I boot my computer and set the tray font size manually. 

![screenshot from 2017-01-15 12-16-24](https://cloud.githubusercontent.com/assets/426992/21966839/609678a8-db1f-11e6-88fa-fb774c8ee976.png)

**Comment by jderose9** [comment]
Thanks for reporting this! I was able to reproduce it.

**Comment by jderose9** [comment]
@RomanShumikhin Are you able to test `master` to verify that this is resolved? Thanks!

**Comment by RomanShumikhin** [comment]
@jderose9 , I pulled the latest master, did `make` in the directory and copied that over the currently installed version from gnome extensions web site, rebooted and I am still seeing the problem (I confirmed that the new version is loaded by checking extension's version which was shown as `-1`).

**Comment by jderose9** [comment]
Actually you should see the commit id for the version when installed correctly from github which is currently 4147dfe8aacd702fb97f2ace3de3578ec8e55753.

You can `make install` to build and deploy it to the correct location, then restart.

**Comment by RomanShumikhin** [comment]
@jderose9 ,

I completely uninstalled dash-to-panel, disabled all extensions to exclude any interference from other extensions I use, ran `git pull` again then ran `make install`, rebooted, enabled dash-to-panel then rebooted again and I am still seeing the problem. I rebooted 3 more times with the only enabled extension being dash-to-panel, the problem is still there.

The version is now shown as "4147dfe...".

Thank you very much for trying to fix this problem!

**Comment by jderose9** [comment]
Can you give it a shot again now? Thanks very much!

**Comment by RomanShumikhin** [comment]
That fixed the problem, thank you very much @jderose9 !!! :) :+1: :100:

**Comment by jderose9** [comment]
@RomanShumikhin Great, thanks for testing!
